- name: Echoing in the distance
  hosts: all
  sudo: false
  tasks:
  - name: Variables
    debug: msg="ansible_os_family - {{ ansible_os_family }}"

- name: Bootystrapping developer environment
  hosts: all
  sudo: false
  tasks:
  - name: APT Update Cache
    sudo: true
    apt: update_cache=yes

  - name: APT Safe Upgrade
    sudo: true
    apt: upgrade=safe

  - name: Install libraries using APT
    apt: name={{ item }} state=latest
    sudo: true
    with_items:
      - vim
      - htop
      - zsh
      - curl
      - git



#- name: Bootystrapping plugins
  #hosts: all
  #sudo: false
  #tasks:
    #- name: Backing up existing ~/.zshrc
      #action: shell if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi

    #- name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
      #action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

    #- name: Creating new ~/.zshrc
      #action: shell cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

    #- name: Backing up existing ~/.vimrc
      #action: shell if [ - ~/.vimrc ]; then mv ~/.vimrc{,.orig}; fi

    #- name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
      #action: shell curl http://j.mp/spf13-vim3 -L -o - | sh

